---
title: "Data-Wrangling-Resources"
author: "aaron mamula"
date: "8/3/2020"
output: html_document
---
# {.tabset .tabset-fade .tabset-pills}

Here is a list of resources that I have curated on the topics of vectorization, data manipulation with dplyr and the tidyverse, and a few other assorted gems.

## General Data Manipulation

[The Base R Cheat Sheet](https://rstudio.com/wp-content/uploads/2016/10/r-cheat-sheet-3.pdf) is an incredibly handy desk reference on how to do things like:

* sort a vector
* write a for loop
* index through a vector
* write a conditional (if/then) statement


## Vectorization

1. [This is a great open resource from Alyssa Frazee](http://alyssafrazee.com/2014/01/29/vectorization.html) on "vectorization"

2. [The Software Carpentry folks also have a cool lesson on "vectorization"](https://swcarpentry.github.io/r-novice-gapminder/09-vectorization/)

## ```apply```

1. [Nice Primer on Apply](https://ademos.people.uic.edu/Chapter4.html)

## ```dplyr```

1. [dplyr and "the grammar" of data manipulation](https://dplyr.tidyverse.org/)

2. [A dplyr discussion from UBC's STAT 545 class](https://stat545.com/dplyr-intro.html). Side note: If you really want to geek-out on R-stuff you should definitely follow [Jenny Bryan on the Twitter](https://twitter.com/jennybryan?lang=en).

3. [Data Wrangling with dplyr Cheat Sheet](https://rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf). Another incredibly handy desk reference for folks working in the dplyr environment.

## The Tidyverse

[Hadley Wickham's Primer on Tidyr](https://blog.rstudio.com/2014/07/22/introducing-tidyr/)

[The Tidyverse Cheat Sheet](https://tidyr.tidyverse.org/)

## data.table

I didn't really talk about the ```data.table``` package in this lesson. It is also a pretty popular R package for data wrangling. I know a few people who use it and are big advocates for ```data.table```. In my limited experience ```data.table``` handles large data sets a little better than the other options and I have used it on a few occassions where speed and ability to handle lots of data was important. 

I recommend looking into it and being informed about it...but I can't provide a lot of code-support here because I'm not a regular users.

[A data.table Introduction](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html)

[More data.table practice](https://rpubs.com/kykimeng/intro-to-data-table)

## Misc

1. [WDI: An R Package for getting World Bank Development Indicator Data](https://www.r-project.org/nosvn/pandoc/WDI.html)





